apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "surf-ais-screenshot.fullname" . }}
  labels:
  {{- include "surf-ais-screenshot.labels" . | nindent 4 }}
data:
  nginx-default.conf: |
    {{ .Files.Get .Values.nginx.defaultConf | nindent 4 }}
