apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "surf-ais-screenshot.fullname" . }}
  labels:
  {{- include "surf-ais-screenshot.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.job.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.job.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.job.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
            - name: {{ .Chart.Name }}-worker-init
              image: busybox:1.32
              command: [ 'sh', '-c', 'mkdir -p /data/uploads' ]
              volumeMounts:
                - name: data
                  mountPath: /data
          containers:
            - name: {{ .Chart.Name }}-worker
              image: {{ .Values.job.image.name | quote }}
              imagePullPolicy: {{ .Values.job.image.pullPolicy }}
              env:
                - name: SELENIUM_HOST
                  value: {{ include "surf-ais-screenshot.fullname" . }}-selenium
                - name: AIS_USER
                  valueFrom:
                    secretKeyRef:
                      key: AIS_USERNAME
                      name: {{ include "surf-ais-screenshot.fullname" . }}
                - name: AIS_PASS
                  valueFrom:
                    secretKeyRef:
                      key: AIS_PASSWORD
                      name: {{ include "surf-ais-screenshot.fullname" . }}
              volumeMounts:
                - name: data
                  mountPath: /data
          restartPolicy: Never
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: {{ include "surf-ais-screenshot.fullname" . }}
      backoffLimit: {{ .Values.job.backoffLimit }}
