apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "surf-ais-screenshot.fullname" . }}-nginx
  labels:
    {{- include "surf-ais-screenshot.labels" . | nindent 4 }}
spec:
{{- if not .Values.nginx.autoscaling.enabled }}
  replicas: {{ .Values.nginx.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "surf-ais-screenshot.nginxSelectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.nginx.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "surf-ais-screenshot.nginxSelectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.nginx.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "surf-ais-screenshot.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.nginx.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-nginx
          securityContext:
            {{- toYaml .Values.nginx.securityContext | nindent 12 }}
          image: {{ .Values.nginx.image.name | quote }}
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          volumeMounts:
            - name: data
              mountPath: /usr/share/nginx/html
              readOnly: true
            - name: configmap-nginx
              mountPath: /etc/nginx/conf.d
              readOnly: true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "surf-ais-screenshot.fullname" . }}
        - name: configmap-nginx
          configMap:
            name: {{ include "surf-ais-screenshot.fullname" . }}
            items:
              - key: nginx-default.conf
                path: default.conf
      {{- with .Values.nginx.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nginx.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nginx.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
