apiVersion: v1
kind: Secret
metadata:
  name: {{ include "surf-ais-screenshot.fullname" . }}
  labels:
  {{- include "surf-ais-screenshot.labels" . | nindent 4 }}
type: Opaque
data:
  AIS_USERNAME: {{ .Values.ais.username | b64enc }}
  AIS_PASSWORD: {{ .Values.ais.password | b64enc }}
